version: '2'

services:
  app:
    build: './'
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'

  database:
    build: database/
    restart: always


# version: '2'

# services:
#   app:
#     image: 'jhods16/sunchamps-checkout'
#     depends_on:
#       - 'database'
#     ports: 
#       - '3002:3002'

#   database:
#     image: 'jhods16/sunchamps-checkoutdb'
#     restart: always